### ISSUE TITLE
Update code to use new jbr URL

### ISSUE THREAD

**Issue by arimer** [mbeddr/build.publish.mps#3]
Looks like future JBRs are moved to a new location. We would need to update the code accordingly: 
See for more details discussion here: https://jetbrains-mps.slack.com/archives/C3YUV3YK0/p1621276910371000?thread_ts=1621260698.367000&cid=C3YUV3YK0

**Comment by coolya** [comment]
This repository doesn't host anything related to JBR. 😕

**Comment by arimer** [comment]
Not required.
